name: Access Request
body:
  - type: input
    id: sample-input
    attributes:
      label: Requester Name
      description: Enter Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: sample-input1
    attributes:
      label: Required Access
      description: Mention the permissions that you want
      placeholder: Please mention the required access.
    validations:
      required: true
  
