name: Sample form
description: Create an issue.
assignees:
  - krushnasharma15
body: 
  - type: input
    id: sample-input
    attributes:
      label: Requester Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: sample-input1
    attributes:
      label: Required Access
      placeholder: Please mention the required access.
    validations:
      required: true
