name: Access Request
assignees:
  - krushnasharma15
description: The Requester can use this form for access requests from the SRE team.
body:
  - type: input
    id: sample-input
    attributes:
      label: Requester Name
      description: Enter Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: sample-input1
    attributes:
      label: Required Access
      description: Mention the permissions that you want
      placeholder: Please mention the required access.
    validations:
      required: true
  - type: dropdown
    id: version4
    attributes:
      label: Below Steps will completed from SRE team
      description: Mark done once this step is completed
  - type: dropdown
    id: version
    attributes:
      label: Create a User
      description: Mark done once this step is completed
      options:
         - Done
         - Pending 
  - type: dropdown
    id: version1
    attributes:
      label: Add this user to a particular group
      description: Mark done once this step is completed
      options:
         - Done
         - Pending 
  - type: dropdown
    id: version2
    attributes:
      label: Share credentials over confidential email
      description: Mark done once this step is completed
      options:
         - Done
         - Pending 
  - type: dropdown
    id: version3
    attributes:
      label: Enable MFA
      description: Mark done once this step is completed
      options:
         - Done
         - Pending 
