name: Access Request
assignees:
  - krushnasharma15
description: The Requester can use this form for access requests from the SRE team.
body:
  - type: dropdown
    id: version3
    attributes:
      label: Request type 
      description: Request type new or Change request
      options:
         - New Request
         - Change Request
  - type: dropdown
    id: version4
    attributes:
      label: Department
      description: Mention your Department
      options:
        - Quality Assurance
        - Administrative
        - Management
        - Product Support
        - People Experience
        - Client Coordination
        - Product Engineering
        - Design
        - Product Marketing
        - Informatics
        - Site Reliability Engineering
        - Customer Success
        - Business Process
        - Account
  - type: input
    id: sample-input
    attributes:
      label: Requester Name
      description: Enter Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: sample-input1
    attributes:
      label: Required Access
      description: Mention the permissions that you want
      placeholder: Please mention the required access.
    validations:
      required: true  
  - type: input
    id: sample-input2
    attributes:
      label: Reason for access
      description: Mention the Reason for access
      placeholder: Please mention the Reason.
    validations:
      required: true  
  - type: dropdown
    id: version
    attributes:
      label: Account 
      description: Select the Account on which access is required
      options:
         - Campaigns
         - Event Discovery
         - freedomtix
  - type: dropdown
    id: version1
    attributes:
      label: Priority 
      description: Select priority
      options:
         - low
         - medium
         - high
  - type: textarea
    id: Other
    attributes:
      label: Other details
      description: Other details if any
      # placeholder: Tell us what you see!
      value: "more details"
    validations:
      required: false

