name: Access Request
body: 
  - type: input
    id: sample-input
    attributes:
      label: Requester Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: sample-input1
    attributes:
      label: Required Access
      placeholder: Please mention the required access.
    validations:
      required: true
   - type: dropdown
     id: version
     attributes:
       label: Create a User
       options:
          - Done
          - Pending (Default)
    - type: dropdown
       id: version1
       attributes:
         label: Add this user in a particular group
         options:
            - Done
            - Pending (Default)
