name: Access Request
assignees:
  - krushnasharma15
description: The Requester can use this form for access requests from the SRE team.
body:
  - type: dropdown
    id: RequestType
    attributes:
      label: Request type 
      description: Request type new or Change request
      options:
         - New Request
         - Change Request
  - type: dropdown
    id: Department
    attributes:
      label: Department
      description: Mention your Department
      options:
        - Quality Assurance
        - Administrative
        - Management
        - Product Support
        - People Experience
        - Client Coordination
        - Product Engineering
        - Design
        - Product Marketing
        - Informatics
        - Site Reliability Engineering
        - Customer Success
        - Business Process
        - Account
  - type: input
    id: RequesterName
    attributes:
      label: Requester Name
      description: Enter Name
      placeholder: Enter Name
    validations:
      required: true
  - type: input
    id: RequiredAccess
    attributes:
      label: Required Access
      description: Mention the permissions that you want
      placeholder: Please mention the required access.
    validations:
      required: true  
  - type: input
    id: ReasonForAccess
    attributes:
      label: Reason for access
      description: Mention the Reason for access
      placeholder: Please mention the Reason.
    validations:
      required: true  
  - type: dropdown
    id: Account
    attributes:
      label: Account 
      description: Select the Account on which access is required
      options:
         - Campaigns
         - Event Discovery
         - freedomtix
  - type: dropdown
    id: Priority
    attributes:
      label: Priority 
      description: Select priority
      options:
         - low
         - medium
         - high
  - type: textarea
    id: Other
    attributes:
      label: Other details
      description: Please elaborate in detail, Why access is required? and for which purpose it will be used?
      value: "more details"
    validations:
      required: true
  - type: dropdown
    id: MFA
    attributes:
      label: MFA
      description: Agree to create a MFA once you got the access ? 
      options:
         - Agree
        
  
