name: Access Request
body:
  - type: input
    id: sample-input 1 
    attributes:
      label: Requester Name
      description: Please enter the requester name
      placeholder: Enter requester name here
    validations:
      required: false
