name: ED Deploy

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project'
        required: true
        default: 'yap'
        type: choice
        options:
          - 'ed'
          - 'yap'
      deploy-environment:
        description: 'Deploy to'
        required: true
        default: 'dev-v2'
        type: choice
        options:
          - 'dev'
          - 'dev-v2'
          - 'stg-v2'
          - 'prod'
          - 'stg'
          - 'prd'

jobs:

  deploy-ed:
    name: ED Deploy
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Environment specific AWS Region 
        run: |
          if [ ${{ inputs.project }} == ed ]; then
                
                    echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
                
              else
                if [ ${{ inputs.deploy-environment }} == prod ]; then
                    echo "AWS_REGION is us-east-1"
                    echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
                else
                    echo "AWS_REGION is ap-south-1"
                    echo "AWS_REGION=ap-south-1" >> $GITHUB_ENV
                fi
              fi
            if [ ${{ inputs.project }} == yap ]; then
              echo "Project is Yap"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            else
              echo "Project is ED"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.ED_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.ED_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            fi
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to Amazon ECS cluster
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.4
        with:
          name: ${{ env.STACK_NAME }}
          template: ./.aws/cloudformation.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            ServiceName=${{ env.SERVICE_NAME }},
            EnvironmentName=${{ env.ENVIRONMENT }}
