name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Process Comment
        id: process_comment
        run: |
          # Check if the event is a pull request comment
          if [ "${{ github.event.issue.pull_request }}" != "null" ]; then
            # This is a pull request comment
            echo "This is a pull request comment."

            # Extract the comment body and check for the specific comment text
            COMMENT_BODY=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
            if [[ "$COMMENT_BODY" == "start test"* ]]; then
              echo "Test cases running"
              # Add your action logic here to run the test cases
              # For example, you can use a test runner like pytest, jest, etc.

              # Read the pull request description
              PR_DESCRIPTION=$(cat "./pull_request_description.md")

              # Iterate through the checkpoints in the description
              # Assuming checkpoints are marked with the pattern "- [ ] [x] Checkpoint name"
              while IFS= read -r line; do
                if [[ $line == "- [ ] [x] "* ]]; then
                  # Get the checkpoint name
                  CHECKPOINT_NAME=$(echo "$line" | sed -e 's/- \[ \] \[x\] //')
                  echo "Running test case for checkpoint: $CHECKPOINT_NAME"
                  # Run the specific test case for the checkpoint name
                  # In this example, we will run the 'add' function test case
                  python -m unittest test_module.TestAdd.test_add_function
                  # Mark the checkpoint as completed by updating the description
                  sed -i "s/- \[ \] \[x\] $CHECKPOINT_NAME/- \[x\] \[ \] $CHECKPOINT_NAME/" "./pull_request_description.md"
                fi
              done <<< "$PR_DESCRIPTION"
            else
              echo "Not the specific comment. Skipping..."
            fi
          else 
            # This is not a pull request comment
            echo "Not a pull request comment. Skipping..."
          fi
