name: 5th Part

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Process Comment
        id: process_comment
        run: |
          if [ "${{ github.event.issue.pull_request }}" != "null" ]; then
            COMMENT_BODY=$(echo "${{ github.event.comment.body }}" | tr '[:upper:]' '[:lower:]')
            if [[ "$COMMENT_BODY" == *"start test"* ]]; then
              echo "This is a pull request comment."

              # Extract the parameter from the PR description
              PR_NUMBER=$(echo "${{ github.event.issue.url }}" | awk -F '/' '{print $NF}')
              PR_DESCRIPTION=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.body')

              PARAMETER=$(echo "$PR_DESCRIPTION" | sed -n 's/.*\[\(.*\)\].*/\1/p')
              
              if [ -n "$PARAMETER" ]; then
                # Remove spaces and replace commas with spaces
                PARAMETER=$(echo "$PARAMETER" | tr -d ' ' | tr ',' ' ')
                echo "Parameter extracted from PR description: $PARAMETER"
                
                # Trigger the "PrintNumbersWorkflow" using workflow_dispatch
                curl -X POST \
                  -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Content-Type: application/json" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/workflows/triggered.yml/dispatches" \
                  -d "{\"ref\": \"main\", \"inputs\": {\"param1\": \"$PARAMETER\"}}"
              else
                echo "Parameter not found in the PR description."
              fi
            else
              echo "Not the specific comment. Skipping..."
            fi
          else 
            echo "Not a pull request comment. Skipping..."
          fi
