name: 5th Part

on:
  issue_comment:
    types: [created]

jobs:
  process_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Process Comment
        id: process_comment
        run: |
          # Check if the event is a pull request comment
          if [ "${{ github.event.issue.pull_request }}" != "null" ]; then
            # This is a pull request comment
            echo "This is a pull request comment."

            # Extract the pull request number from the comment
            PR_NUMBER=$(echo "${{ github.event.issue.url }}" | awk -F '/' '{print $NF}')

            # Fetch the pull request description
            PR_DESCRIPTION=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.body')

            # Find the parameter in the pull request description using regex
            if [[ "$PR_DESCRIPTION" =~ \[(.*)\] ]]; then
              PARAMETER="${BASH_REMATCH[1]}"
              echo "Parameter extracted from comment: $PARAMETER"

              # Create a JSON payload with the input parameters
              PAYLOAD="{\"ref\": \"main\", \"inputs\": {\"param1\": \"$PARAMETER\"}}"

              # Trigger the "PrintNumbersWorkflow" using workflow_dispatch
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Content-Type: application/json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/print_numbers.yml/dispatches" \
                -d "$PAYLOAD"
            else
              echo "Parameter not found in the pull request description."
            fi
          else 
            # This is not a pull request comment
            echo "Not a pull request comment. Skipping..."
          fi
