name: PrintNumbersWorkflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output (Received Parameter)
        run: |
          echo "Received Parameter in Print Numbers step: ${{ github.event.inputs.param1 }}"
