name: Print Numbers Workflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Print Parameters
        run: |
          echo "Parameter 1: ${{ toJson(workflow_run.outputs) }}"
