name: PrintNumbersWorkflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output (Received Parameter)
        run: |
          echo "Received Parameter:"
          echo "COMMENT_PARAMETER=${{ github.event.workflow_run.inputs.param1 }}"

      - name: Print Parameter
        run: |
          echo "Received Parameter in Print Numbers step:"
          echo "COMMENT_PARAMETER=${{ github.event.workflow_run.inputs.param1 }}"
