name: Print Numbers Workflow

on:
  repository_dispatch:
    types: [my-event]

jobs:
  print_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Print Parameters
        run: |
          echo "Parameter 1: ${{ github.event.client_payload.param1 }}"
          echo "Parameter 2: ${{ github.event.client_payload.param2 }}"
          echo "Parameter 3: ${{ github.event.client_payload.param3 }}"
          echo "Parameter 4: ${{ github.event.client_payload.param4 }}"
