name: PrintNumbersWorkflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: true
      param3:
        description: 'Parameter 3'
        required: true
      param4:
        description: 'Parameter 4'
        required: true

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Numbers
        run: |
          # Get the array from the environment variable set by the first script
          COMMENT_ARRAY=($COMMENT_ARRAY)

          # Print numbers based on the array length
          for element in "${COMMENT_ARRAY[@]}"; do
            echo "$element"
          done
