name: Print Numbers Workflow

on:
  workflow_run:
    workflows: ["5th Part"]  # Replace with the actual name of the triggering workflow
    types:
      - completed

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Print Numbers
        run: |
          echo "1"
          echo "2"
          echo "3"
          echo "4"
