name: PrintNumbersWorkflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output (Received Parameter)
        run: |
          PARAMETER="${{ github.event.inputs.param1 }}"
          echo "Received Parameter in Print Numbers step: $PARAMETER"

          # Split the parameter string into an array
          IFS=', ' read -r -a PARAMETER_ARRAY <<< "$PARAMETER"

          # Loop through the array and print each element
          for element in "${PARAMETER_ARRAY[@]}"; do
            echo "Element: $element"
          done
