name: Print Numbers Workflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Print Parameters
        run: |
          echo "Parameter 1: ${{ github.event.workflow_run.outputs.param1 }}"
          echo "Parameter 2: ${{ github.event.workflow_run.outputs.param2 }}"
          echo "Parameter 3: ${{ github.event.workflow_run.outputs.param3 }}"
          echo "Parameter 4: ${{ github.event.workflow_run.outputs.param4 }}"
