name: PrintNumbersWorkflow

on:
  workflow_run:
    workflows: ["5th Part"]
    types:
      - completed

jobs:
  print_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Output (Received Parameter)
        run: |
          echo "Received Workflow Run Event Payload:"
          echo "${{ toJson(github.event.workflow_run) }}"

      - name: Print Parameter
        run: |
          PARAMETER="${{ github.event.workflow_run.inputs.param1 }}"
          echo "Received Parameter in Print Numbers step: $PARAMETER"
